# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hcheck',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
