# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180129_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(max_length=200),
        ),
    ]
