# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category_id',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='front.Category'),
        ),
    ]
