# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20180130_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_id',
            new_name='name',
        ),
    ]
