# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20180130_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
