# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20180130_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
