# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='priority',
        ),
    ]
