# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='priority',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
