# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_check_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
