# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180131_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='priority',
            field=models.CharField(blank=True, default='3', max_length=50),
        ),
    ]
