# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180131_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='priority',
            field=models.IntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low'), (3, 'None')], default=3),
        ),
    ]
