# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180117_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_interval',
        ),
        migrations.RemoveField(
            model_name='check',
            name='nag_time',
        ),
    ]
