# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180117_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='apikey',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='username',
        ),
    ]
