# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180119_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='often',
        ),
    ]
