# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180118_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_after',
        ),
        migrations.RemoveField(
            model_name='check',
            name='nag_mode',
        ),
        migrations.AlterField(
            model_name='check',
            name='alert_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
