# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_check_often'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='ping_diff',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
